/** App changelog, newest first — shown in Settings → What's new. */

export interface ChangelogEntry {
  version: string
  date: string
  title: string
  items: string[]
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "0.12.0",
    date: "2026-07-13",
    title: "GPU rendering, punchier Shorts, and a Windows render fix",
    items: [
      "Renders can now use your GPU: a new Video encoder setting in Settings > Output uses NVIDIA, Intel, or AMD hardware when it is available and quietly falls back to CPU when it is not",
      "The Short can have its own drop length: set Short drop length in Settings, and when it differs from the full video a separate punchier Short is rendered (4 bars by default against 8 for the full video). Leave it on Same as full video to keep a single render for both",
      "Full video drop length and Short drop length are now separate settings, both editable in Settings > Mix",
      "Each mix in the Mixes panel now has Full video and Short tabs, so you can play and download either version right there",
      "Fixed rendering on Windows, where the title and branding step could fail and stop the whole render",
      "Auto-Mix is now Beta and the Auto-Mix button is hidden by default. Turn on Enable Auto-Mix button in Settings > Interface to show it; otherwise a playlist just feeds Import and Choose",
      "Imported tracks are now analyzed automatically, so they are ready to mix the moment the import finishes",
      "The EDMPAPA intro now plays even without the large source file: a lightweight intro ships with the app and is used as a fallback (this also brings the intro to the packaged builds)",
      "New Short overlay setting: turn it off for a clean full-width Short with no EDMPAPA template, the track titles still burned in",
      "Add a custom Short title: a bold boxed caption (TikTok/CapCut style) burned near the top of the Short, set in Settings > Output",
      "Short captions use connected per-line rounded boxes that hug each line (curving inward on shorter lines) with full-color emoji, like TikTok/CapCut captions",
      "Shorts show just the track name by default (artist + track ran too long); turn on Show artist name in Settings to include the artist",
      "The live Short preview in the Render dialog now renders with the exact same engine as the output (same font, color emoji, and smoothly rounded caption boxes), so it matches the final Short, and it stays pinned on the right",
      "The Render dialog lists the selected tracks with a play button to check each from its drop, with a playback progress fill in the accent color",
      "You can close the Render dialog while a render runs: a floating indicator shows the progress with a button to reopen it",
      "The EDMPAPA intro on the full video is now more subtle (lower opacity) so it does not wash out the footage",
      "The Short video now zooms to fill the whole vertical frame (aspect kept, edges cropped) instead of leaving black bars",
      "New Short end card toggle (the 'watch the full video' card) in Settings, off by default",
      "The Short's artist and track name show together (stacked) at the bottom and pop in on the drop, clear of the YouTube Shorts buttons and caption",
      "New Short length setting (5 to 15 seconds, or full) to keep the teaser punchy, and a separate Short font (Cubano by default) so Shorts can look different from the full video",
      "New option to render only the Short and skip the full video, for quick vertical clips (also available right in the Render dialog)",
      "Settings are reorganized: a dedicated Shorts section, and a new Debug section with a reset-to-defaults button and a shortcut to the developer console",
      "Right-click now shows a Cut / Copy / Paste / Select all menu that works everywhere, including the desktop app",
      "The app ships with its own icon, and the browser tab favicon matches it",
      "Dialogs now open and close with a smooth animation",
      "New defaults: clean Shorts (no EDMPAPA overlay), full-length Shorts, and Cubano as the title font",
      "The Short preview is now bigger, centered, and keeps its true vertical aspect ratio",
      "Smoother open and close animation on all dialogs, with a soft backdrop blur",
      "Removed the max tracks field from the playlist bar. Use Choose to pick exactly which tracks to import or mix",
      "The status panel below the playlist bar now closes when you click anywhere outside it, not only its close button",
      "The render window no longer runs off the screen when a mix finishes, it scrolls instead",
      "A few settings return to their defaults after this update",
    ],
  },
  {
    version: "0.11.0",
    date: "2026-07-06",
    title: "Every export gets its own tidy folder",
    items: [
      "Each render now lands in its own folder named after the export, holding the full video, the vertical Short, and the verification report together, instead of loose files piled in the exports folder",
      "The Mixes panel shows one entry per mix now (the Short is tucked in with it, not listed as a separate item)",
      "Deleting a mix removes its whole folder in one go, Short and report included",
      "Existing mixes from before this change still show up and play as normal",
    ],
  },
  {
    version: "0.10.0",
    date: "2026-07-05",
    title: "Live drop length and an accent-matched timeline",
    items: [
      "Changing Drop length in Settings now applies everywhere instantly: drop previews loop the new length, the trim end marker slides to match, and every clip already in the mix re-trims to the new bar count",
      "A drop looping while you change the setting keeps playing and simply wraps at the new length, no restart",
      "Set Drop length back to Auto and everything returns to the detected drop ends",
      "Manual trims are safe: markers only move when the setting itself changes",
      "The timeline waveform now takes your accent color instead of always purple, re-tinting live when you pick a new accent",
      "Trim handles and the selection shading follow the accent too",
    ],
  },
  {
    version: "0.9.0",
    date: "2026-07-05",
    title: "Pick your title font, or upload your own",
    items: [
      "New Title font setting in Settings > Output: choose the font used for the track titles burned into the video and the Short",
      "Bebas Neue is the new default title font; Cubano ships as an alternative",
      "Upload any TTF or OTF font file and it joins the list, ready to use in the next render",
      "The live preview shows titles in the selected font, matching the final render",
      "Manual renders now honor the Short, file name, drop length, and video cut settings (they were silently ignored before)",
    ],
  },
  {
    version: "0.8.0",
    date: "2026-07-05",
    title: "4K downloads with a quality picker",
    items: [
      "YouTube imports now grab the highest resolution available (4K and beyond), downloading the best video and audio streams separately and merging them",
      "New Downloads section in Settings lets you cap import quality: Best available, 4K, 2K, 1080p, or 720p",
      "The cap applies to Import, Auto-Mix, and playlist track selections alike",
      "Mix Editor clips from a set now show the song title from the tracklist instead of the file name",
      "Rendered mixes are named after the source video plus the date and time (no overlaps), with a Settings option for timestamp-only names",
      "Drops already added to the mix are highlighted again in the track list (green row with a check)",
      "Settings controls line up: one control height and consistent label spacing throughout",
      "Mix Editor panel is more compact with tighter padding around clips",
      "Delete all mixes in one go from the Mixes panel (with a confirm step)",
      "YouTube Shorts: every render also produces a vertical Short with the first minute of the mix inside the EDMPAPA template, artist and track name switching with each drop, and a watch-the-full-video end card; turn it off in Settings > Output",
      "Short drops fixed: real 8-bar drops no longer collapse to 4 bars when the energy scan undershoots by half a bar (Chicken Soup, Ghetto Shout Out and friends)",
      "New Drop length setting in Settings > Mix: Auto or a forced 4/8/12/16 bars per drop, applied when adding drops and in Auto-Mix",
      "The render dialog shows the finished Short next to the full video in tabs",
    ],
  },
  {
    version: "0.7.0",
    date: "2026-07-05",
    title: "Paste tracklists straight from 1001tracklists",
    items: [
      "Select a whole 1001tracklists page, paste it as is, and the tracklist is extracted automatically: song number blocks, vote counts, Save buttons, and uploader names are stripped away",
      "Record labels after titles (like REVEALED) are removed, and w/ acappella or mashup overlay lines are folded into the main track",
      "The tracklist dialog shows a live preview of every recognized song and timestamp before you save",
      "Dialogs are larger across the app, so tracklists, changelogs, and track choosers get room to breathe",
    ],
  },
  {
    version: "0.6.0",
    date: "2026-07-05",
    title: "Clean audio, hard cuts & self-verifying renders",
    items: [
      "Audio pipeline is float end to end: hot festival masters (peaks above full scale) no longer clip anywhere",
      "Loudness set by pure linear gain plus one final peak limiter; the pumping distortion from dynamic normalization is gone",
      "Video transitions are hard cuts on the incoming build (the natural editor cut), with titles switching on the cut",
      "Every drop in a set gets a full 8-bar body, so no more 2-second drops",
      "Kick anchors validated against the actual drop slam (fixes drops that started a beat early)",
      "Every render verifies itself: seam kick timing, loudness, true peak, and on-screen titles, with a report saved next to the export",
      "Long titles shorten smartly (never losing the track identity), then scale or wrap, always inside safe margins",
      "Raw track playback in the app auto-levels like YouTube does, so hot sources don't blow out",
      "Drop detection runs per song inside a set's tracklist, so every song gets its own candidates",
      "Track list groups each song's drops as a folder tree: confidence-ranked with main (green), alt (yellow), weakest (red) badges",
      "The main drop is always the highest-confidence candidate; alternates stay one click away, and song titles are editable in place",
    ],
  },
  {
    version: "0.5.0",
    date: "2026-07-04",
    title: "Full DJ sets & faster renders",
    items: [
      "Hour-long sets detect every drop (cap scales with duration)",
      "Paste or auto-fetch a tracklist to label drops with song names; one drop per song",
      "Search matches drop titles and filters a set down to the hit",
      "Add all drops in one click; re-analyze button on any track",
      "Renders run clips in parallel with fused encodes (much faster), plus a resolution picker (480p to 4K)",
      "Hosted app on GitHub Pages talks to your local backend; accent colors, credits, and privacy notes in Settings",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-07-04",
    title: "Intro, outro & job control",
    items: [
      "Intro animation blended over the first buildup, ending exactly on the first drop (title hidden underneath)",
      "20s black outro reserved for YouTube end screens",
      "Cancel button for imports, Auto-Mix jobs, and renders",
      "Bulk rename modal with online title lookup (Deezer/iTunes)",
      "Select-all delete in the track list",
      "Live preview simulates the intro, branding, titles, and outro",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-07-04",
    title: "Ear-tight transitions",
    items: [
      "Per-seam kick alignment measured from the actual audio, so drops land on the grid",
      "True local tempo per drop (fixes ~1% BPM-estimate drift across blends)",
      "2-bar vocal lead-in on every transition, with the outgoing track ducking fast so the incoming vocal is clear",
      "Titles switch exactly on each drop; video fades locked to the audio timeline",
      "Playlist track chooser with whole-playlist option",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-07-04",
    title: "Live preview & layout",
    items: [
      "Instant in-browser mix preview with the main player as a branded video monitor",
      "Auto-Mix bar moved into the header so the video and timeline fit above the fold",
      "Library split into videos/imports and videos/exports",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-07-04",
    title: "Detection & editing",
    items: [
      "Bass-gated drop detection, so vocal and intro sections are no longer picked as drops",
      "Drop starts land on the track's real pre-kick breath (per-track, not a fixed offset)",
      "Timeline zoom (Ctrl+scroll), smooth playhead follow, play/pause transport",
      "Track rename/copy, per-job progress logs, spacebar play/pause",
    ],
  },
]

/** Current app version = the newest changelog entry. */
export const APP_VERSION = CHANGELOG[0]?.version ?? "0.0.0"
